alias neoc='clear && echo "" && neofetch'
alias ls='ls --color=auto'
alias ll='ls -la'
alias py='python3'
alias python='python3'
alias vim='nvim'
alias vi='nvim'
alias cls='clear'
alias gits='git status'
alias gitd='git diff'
