[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [".venv"]

[tool.ruff]
line-length = 79
indent-width = 4
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint]
select = ["D", "W", "E", "F", "B", "I", "ANN"]
ignore = ["D100", "D104", "D105", "D203", "D205", "D212"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F402"]
"test_*.py" = ["D", "ANN", "E501"]
