format = """
[◖](#c678dd)\
$username\
$hostname\
\\[$directory\\]\
$git_branch\
$git_status\
\\$ 
"""

add_newline = false

[username]
show_always = true
style_user = 'fg:#98c379'
style_root = 'fg:#98c379'
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = false
style = 'fg:#56b6c2'
format = '[$hostname]($style)'
disabled = false

[directory]
style = 'fg:#c678dd'
format = '[$path]($style)'
truncation_length = 3
truncation_symbol = '../'

[git_branch]
symbol = ''
style = 'fg:#e5c07b'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'fg:#e5c07b'
format = '[$all_status$ahead_behind ]($style)'
